#!/bin/sh

CONFDIR="${ROOT_DIR}/etc/nfqws"
CONFFILE=$CONFDIR/nfqws.conf
LISTLOG="${ROOT_DIR}/var/log/nfqws.log"
INIT_SCRIPT="${ROOT_DIR}/etc/init.d/S51nfqws"
INIT_SCRIPT_OWRT="${ROOT_DIR}/etc/init.d/nfqws-keenetic"
NFQWS_BIN="${ROOT_DIR}/usr/bin/nfqws"

stop_func() {
  if [ -f "$INIT_SCRIPT" ]; then
    $INIT_SCRIPT stop
  elif [ -f "$INIT_SCRIPT_OWRT" ]; then
    $INIT_SCRIPT_OWRT stop
  fi
}

start_func() {
  if [ -f "$INIT_SCRIPT" ]; then
    $INIT_SCRIPT start
  elif [ -f "$INIT_SCRIPT_OWRT" ]; then
    $INIT_SCRIPT_OWRT start
  fi
}

isp_interface_func() {
  route | grep '^default' | grep -o '[^ ]*$'
}

ipv6_enabled_func() {
  # $1 - interface, e.g. eth3
  enabled=$(ip -f inet6 addr show dev "$1" 2>/dev/null | grep "scope global")
  return $([ -z "$enabled" ])
}

fast_install_func() {
  NFQWS_INSTALL_TYPE="install"
  if [ -f "${ROOT_DIR}/tmp/nfqws_install_type" ]; then
    # Set in preinst script
    NFQWS_INSTALL_TYPE=$(cat "${ROOT_DIR}/tmp/nfqws_install_type")
    rm -f "${ROOT_DIR}/tmp/nfqws_install_type"
  fi

  case "$NFQWS_INSTALL_TYPE" in
    install)
      # Interface
      DEF_IFACE=$(isp_interface_func)
      sed -i -E "s#ISP_INTERFACE=\".+\"#ISP_INTERFACE=\"$DEF_IFACE\"#" $CONFFILE

      # IPv6
      IPV6=$(ipv6_enabled_func "$DEF_IFACE" && echo 1 || echo 0)
      sed -i -E "s#IPV6_ENABLED=(1|0)#IPV6_ENABLED=$IPV6#" $CONFFILE

      # Config paths
      if [ -f "$INIT_SCRIPT_OWRT" ]; then
        sed -i -E "s#/opt/#/#g" $CONFFILE
      fi

      echo "Installation successful"
      ;;
    *)
      # Do nothing
      ;;
  esac
}

remove_binary_func() {
  rm -f "$NFQWS_BIN"
}

remove_all_files_func() {
  rm -f $LISTLOG
  echo -e "\nRemove lists and config? y/N"
  read yn
  case $yn in
    [Yy]* )
      rm -rf $CONFDIR
      ;;
  esac
}

install_binary_func() {
  OPKG_CONF="${ROOT_DIR}/etc/opkg.conf"

  if [ -f "$OPKG_CONF" ]; then
    ARCH=$(cat "$OPKG_CONF" | grep -oE 'mips-3|mips_|mipsel-3|mipsel_|aarch64-3|aarch64_|armv7' | head -n 1)
    case "$ARCH" in
      "mips-3"|"mips_") ARCH="mips" ;;
      "mipsel-3"|"mipsel_") ARCH="mipsel" ;;
      "aarch64-3"|"aarch64_") ARCH="aarch64" ;;
      "armv7") ARCH="armv7" ;;
    esac
  fi

  if [ -z $ARCH ]; then
    ARCH=$(uname -m | grep -oE 'mips|mipsel|aarch64|armv7')
    if [ "$ARCH" == "mips" ]; then
      if grep -qE 'system type.*MediaTek' /proc/cpuinfo; then
        ARCH="mipsel"
      fi
    fi
  fi

  if [ -z $ARCH ]; then
    echo "Failed to detect architecture"
    exit 1
  fi

  echo "Detected arch: $ARCH"

  cp -f "${ROOT_DIR}/tmp/nfqws_binary/nfqws-$ARCH" "${ROOT_DIR}/usr/bin/nfqws"
  chmod +x "${ROOT_DIR}/usr/bin/nfqws"
  rm -rf "${ROOT_DIR}/tmp/nfqws_binary"
}
