#!/bin/sh

source $(dirname $0)/nfqws-keenetic.common

install_binary_func() {
  ARCH=$(cat /opt/etc/opkg.conf | grep -oE 'mips-3|mipsel-3|aarch64-3|armv7' | head -n 1)
  case "$ARCH" in
    "mips-3") ARCH="mips" ;;
    "mipsel-3") ARCH="mipsel" ;;
    "aarch64-3") ARCH="aarch64" ;;
    "armv7") ARCH="armv7" ;;
  esac

  if [ -z $ARCH ]; then
    echo "Failed to detect architecture"
    exit 1
  fi
  echo "Detected arch: $ARCH"

  cp -f "/tmp/nfqws_binary/nfqws-$ARCH" "/opt/usr/bin/nfqws"
  chmod +x /opt/usr/bin/nfqws
  rm -rf /tmp/nfqws_binary
}

# Stop service if exist
stop_func

# Install binary
install_binary_func

# Install wizard
install_func

# Starting Services
start_func

exit 0
