#!/bin/sh

CONFDIR=/opt/etc/nfqws
LISTLOG=/opt/var/log/nfqws.log

remove_binary_func() {
  rm -f /opt/usr/bin/nfqws
}

remove_all_files_func() {
  rm -f $LISTLOG
  echo -e "\nRemove lists and config? y/N"
  read yn
  case $yn in
    [Yy]* )
      rm -rf $CONFDIR
      ;;
  esac
}

# Remove binary file
remove_binary_func

case "$1" in
  upgrade)
    # Do nothing
    ;;
  *)
    # Remove all data
    remove_all_files_func

    echo "Unnstallation successful"
    ;;
esac

exit 0
