#!/bin/sh

source $(dirname $0)/nfqws-keenetic.common

install_binary_func() {
  CONFFILE="/opt/etc/opkg.conf" # Keenetic
  if [ ! -f "/opt/etc/opkg.conf" ]; then
    CONFFILE="/etc/opkg.conf" # OpenWRT
  fi

  if [ -f "$CONFFILE" ]; then
    ARCH=$(cat "$CONFFILE" | grep -oE 'mips-3|mips_|mipsel-3|mipsel_|aarch64-3|aarch64_|armv7' | head -n 1)
    case "$ARCH" in
      "mips-3") ARCH="mips" ;;
      "mips_") ARCH="mips" ;;
      "mipsel-3") ARCH="mipsel" ;;
      "mipsel_") ARCH="mipsel" ;;
      "aarch64-3") ARCH="aarch64" ;;
      "aarch64_") ARCH="aarch64" ;;
      "armv7") ARCH="armv7" ;;
    esac
  fi

  if [ -z $ARCH ]; then
    ARCH=$(uname -m | grep -oE 'mips|mipsel|aarch64|armv7')
    if [ "$ARCH" == "mips" ]; then
      if grep -qE 'system type.*MediaTek' /proc/cpuinfo; then
        ARCH="mipsel"
      fi
    fi
  fi

  if [ -z $ARCH ]; then
    echo "Failed to detect architecture"
    exit 1
  fi

  echo "Detected arch: $ARCH"

  cp -f "/tmp/nfqws_binary/nfqws-$ARCH" "/opt/usr/bin/nfqws"
  chmod +x /opt/usr/bin/nfqws
  rm -rf /tmp/nfqws_binary
}

# Stop service if exist
stop_func

# Install binary
install_binary_func

# Install wizard
install_func

# Starting Services
start_func

exit 0
