#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0

source $(dirname $0)/nfqws-keenetic.env
source $(dirname $0)/nfqws-keenetic.common

# Install binary
install_binary_func

# Install wizard
install_func

# Default postinst
[ -f ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@
