#!/bin/sh

source $(dirname $0)/env

CONFFILE="${ROOT_DIR}/etc/nfqws/nfqws.conf"
LISTFILE="${ROOT_DIR}/etc/nfqws/user.list"

# Set `install` or `upgrade` for postinst script
echo "$1" > "${ROOT_DIR}/tmp/nfqws_install_type"

# Migrations
NEED_MIGRATION_CONF=0
NEED_MIGRATION_LIST=0

CURRENT_VERSION=3  # TODO: Set from current config
INSTALLED_VERSION=$(grep -E '^CONFIG_VERSION=' "$CONFFILE" 2>/dev/null | grep -oE '[0-9]+$')

if [ -z "$INSTALLED_VERSION" ]; then
  NEED_MIGRATION_CONF=1
elif [ "$INSTALLED_VERSION" -lt "$CURRENT_VERSION" ]; then
  NEED_MIGRATION_CONF=1
fi

if [ $NEED_MIGRATION_CONF -ne 0 ]; then
  if [ -f "$CONFFILE" ]; then
    # Old config
    mv "$CONFFILE" "$CONFFILE-old"
    echo "Old configuration file was moved to $CONFFILE-old"
  fi

  # We need clean install
  echo "install" > "${ROOT_DIR}/tmp/nfqws_install_type"
fi

if [ $NEED_MIGRATION_LIST -ne 0 ]; then
  if [ -f "$LISTFILE" ]; then
    # Old list
    mv "$LISTFILE" "$LISTFILE-old"
    echo "user.list file was moved to $LISTFILE-old"
  fi
fi

exit 0
