#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0

service lighttpd start
service lighttpd reload

ip_addr=$(ip -f inet addr show dev br-lan 2>/dev/null | grep inet | sed -n 's/.*inet \([0-9.]\+\).*/\1/p')
echo "NFQWS Web Interface installed: http://$ip_addr:90"

# Default postinst
[ -f ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@
