#!/bin/sh

# Fix conflict with keenetic webdav server: https://github.com/Entware/entware-packages/pull/27
sed -i -E "s/^PROCS=lighttpd$/PROCS=\/opt\/sbin\/lighttpd/" /opt/etc/init.d/S80lighttpd

/opt/etc/init.d/S80lighttpd start
/opt/etc/init.d/S80lighttpd reconfigure

ip_addr=$(ip -f inet addr show dev br0 2>/dev/null | grep inet | sed -n 's/.*inet \([0-9.]\+\).*/\1/p')
echo "NFQWS Web Interface installed: http://$ip_addr:90"

exit 0
