#!/bin/sh

/opt/etc/init.d/S80uhttpd start

ip_addr=$(ip -f inet addr show dev br0 2>/dev/null | grep inet | sed -n 's/.*inet \([0-9.]\+\).*/\1/p')
echo "NFQWS Web Interface installed: http://$ip_addr:88/nfqws/"

exit 0
