#!/bin/sh

/etc/init.d/lighttpd start
/etc/init.d/lighttpd reload

ip_addr=$(ip -f inet addr show dev br-lan 2>/dev/null | grep inet | sed -n 's/.*inet \([0-9.]\+\).*/\1/p')
echo "NFQWS Web Interface installed: http://$ip_addr:90"

exit 0
