#!/bin/sh
# Entware startup script

PATH=/opt/sbin:/opt/bin:/opt/usr/sbin:/opt/usr/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH=/lib:/usr/lib:/opt/lib:/opt/usr/lib

NFQWS_BIN="/opt/usr/bin/nfqws"
CONFFILE="/opt/etc/nfqws/nfqws.conf"
PIDFILE="/opt/var/run/nfqws.pid"
