name: Test build

on:
  workflow_dispatch:
    branches:
      - openwrt_apk

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-openwrt:
    runs-on: ubuntu-latest

    container:
      image: openwrt/sdk:latest
      options: --user root

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Bump version file
      uses: francktrouillez/auto-bump-version-file@v1
      with:
        file: 'VERSION'

    - name: Summary
      run: |
        echo '```' >> $GITHUB_STEP_SUMMARY
        ls ./ >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
