name: Test build

on:
  workflow_dispatch:
    branches:
      - openwrt_apk

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-openwrt:
    runs-on: ubuntu-latest

    container:
      image: openwrt/sdk:latest
      options: --user root

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Bump version file
      uses: francktrouillez/auto-bump-version-file@v1
      with:
        file: 'VERSION'

    - name: Init SDK
      working-directory: /builder
      run: |
        HOME=/builder ./setup.sh

    - name: Copy keys
      env:
        OPENWRT_PUBLIC_KEY: ${{ secrets.OPENWRT_PUBLIC_KEY }}
        OPENWRT_SECRET_KEY: ${{ secrets.OPENWRT_SECRET_KEY }}
        OPENWRT_APK_PUBLIC_KEY: ${{ secrets.OPENWRT_APK_PUBLIC_KEY }}
        OPENWRT_APK_SECRET_KEY: ${{ secrets.OPENWRT_APK_SECRET_KEY }}
      run: |
        echo "$OPENWRT_SECRET_KEY" > /builder/key-build
        echo "$OPENWRT_PUBLIC_KEY" > /builder/key-build.pub
        echo "$OPENWRT_APK_SECRET_KEY" > /builder/private-key.pem
        echo "$OPENWRT_APK_PUBLIC_KEY" > /builder/public-key.pem

    - name: Build openwrt packages
      id: build
      working-directory: /builder
      run: |
        echo "src-link nfqws $GITHUB_WORKSPACE/openwrt" > feeds.conf
        ./scripts/feeds update nfqws
        ./scripts/feeds install -a -p nfqws
        make defconfig
        make CONFIG_USE_APK=y package/nfqws-keenetic/compile V=s
        make CONFIG_USE_APK=y package/index V=s
        make CONFIG_USE_APK= package/nfqws-keenetic/compile V=s
        make CONFIG_USE_APK= package/index V=s
        ls -la /builder/bin/packages/x86_64/nfqws/

    - name: Upload files
      if: steps.build.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: openwrt
        path: /builder/bin/packages/x86_64/nfqws/*
        if-no-files-found: error

  build-entware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Bump version file
      uses: francktrouillez/auto-bump-version-file@v1
      with:
        file: 'VERSION'

    - name: Build entware packages
      run: make entware

    - name: Build entware web
      run: make web-entware

    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: entware
        path: ./out/*.ipk
        if-no-files-found: error

  test-release:
    runs-on: ubuntu-latest
    needs: [build-openwrt, build-entware]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Bump version file
      uses: francktrouillez/auto-bump-version-file@v1
      with:
        file: 'VERSION'

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: out
        merge-multiple: true

    - name: Display artifacts
      run: ls -R out
